version: "3.9"

services:

  rabbitmq:
    build: ./dockercompilers/rabbitmq
    container_name: compiler-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  java-runner:
    build: ./dockercompilers/java-runner
    image: java-runner

  python-runner:
    build: ./dockercompilers/python-runner
    image: python-runner

  c-runner:
    build: ./dockercompilers/c-runner
    image: c-runner

  cpp-runner:
    build: ./dockercompilers/cpp-runner
    image: cpp-runner

  js-runner:
    build: ./dockercompilers/javascript-runner
    image: js-runner


